title: <p align="center"> Sandip Mahato
logo: /assets/img/logo.png


description:
  <p align="center">
  <a href="https://github.com/sandipm26">GitHub</a>
  
  <br>   
  I'm working on Data Engineering, Big Data, Spark, Machine learning problems.
  Also handing the Big Data in Google Cloud.
  Worked with IBM Canada at Big Data Analytics team.
  <br>
  </p>
  
  
  
theme: jekyll-theme-minimal
